#if JUSTTRACK_IRONSOURCE_INTEGRATION
using System;
using JustTrack;

// DO NOT EDIT - AUTOMATICALLY GENERATED BY THE JUSTTRACK SDK

namespace JustTrackInjected {
    public class IronSourceAdapterImpl: IronSourceAdapter {
        public void SetIronSourceOnImpressionHandler(Action<object> proxy) {
            IronSourceEvents.onImpressionSuccessEvent += (eventObj) => proxy(eventObj);
        }
    }
}
#endif
